# Generated by Django 3.1.3 on 2023-05-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20200507_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
